name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-7b6e6bad-41d2-452f-974
  PROJECT_NUMBER: "379699849683"
  REGION: asia-southeast2

  SERVICE: devops-test-app-dev
  REPOSITORY: devops-test-app-repository

  WORKLOAD_IDENTITY_PROVIDER: projects/379699849683/locations/global/workloadIdentityPools/github-pool/providers/github-provider

  SERVICE_ACCOUNT: github-actions-deployer@project-7b6e6bad-41d2-452f-974.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/devops-test-app:${{ github.sha }}

          docker build \
            -t $IMAGE_URI \
            ./app

      - name: Push Docker Image
        run: |
          IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/devops-test-app:${{ github.sha }}

          docker push $IMAGE_URI

      - name: Deploy Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/devops-test-app:${{ github.sha }}

      - name: Show Cloud Run URL
        run: |
          echo "Application URL:"
          echo "${{ steps.deploy.outputs.url }}"
